name: PHP Composer

on:
  push:
    tags:
      - 'v*'
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: Cache Composer packages
      #   id: composer-cache
      #   uses: actions/cache@v2
      #   with:
      #     path: vendor
      #     key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --no-suggest

      - uses: montudor/action-zip@v0.1.1
        with:
          args: zip -qq -r release.zip .

      - uses: actions/upload-artifact@v2
        with:
          name: vendor.zip









    steps:
    - uses: actions/checkout@v1
    - run: composer install --ansi --no-progress --no-interaction --prefer-dist
    - uses: montudor/action-zip@v0.1.1
      with:
        args: zip -qq -r vendor.zip vendor
    - uses: actions/upload-artifact@v2
      with:
        name: vendor.zip





    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
